<?php

namespace App\Services\Performance;

use App\Models\Creative;
use App\Support\MetricsSummary;
use RuntimeException;

/**
 * Placeholder for the future Meta Ads source.
 *
 * Nothing is implemented on purpose: there is no OAuth flow, no API client and no
 * synthetic data. It exists so the rest of the app is written against
 * {@see PerformanceProvider} and Meta can be added later by filling this in —
 * pulling campaign/ad-set/ad spend and mapping it onto creatives through the
 * naming convention and UTM content already generated by the app.
 */
class MetaAdsPerformanceProvider implements PerformanceProvider
{
    public function key(): string
    {
        return 'meta';
    }

    public function label(): string
    {
        return config('integrations.performance.meta.label');
    }

    public function isAvailable(): bool
    {
        return false;
    }

    public function totalsFor(Creative $creative): MetricsSummary
    {
        throw new RuntimeException('L\'intégration Meta n\'est pas encore disponible.');
    }
}
